# TODO: 补充docker compose配置文件
version: '3'
services:
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:8.1
    volumes:
      - "/home/ubuntu/mysql:/var/lib/mysql"
    # env_file: .env
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2021011815
      MYSQL_DATABASE: thss
      TZ: Asia/Shanghai
    command: ['mysqld' ,'--character-set-server=utf8mb4' ,'--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  app:
    container_name: app
    restart: always
    build: .
    command: >
      bash -c "python manage.py makemigrations --settings=wechat.settings &&
            python manage.py migrate --settings=wechat.settings &&
             DJANGO_SETTINGS_MODULE=wechat.settings gunicorn -w4 -b 0.0.0.0:8000 --log-level=debug wechat.wsgi"
    volumes:
      - .:/code/
      # - static-volume:/code/build/
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - web_network
      - db_network   
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      # - static-volume:/code/build/
      - ./nginx:/etc/nginx/conf.d
      - .:/code
    depends_on:
      - app
    networks:
      - web_network

networks:
    web_network:
      driver: bridge
    db_network:
      driver: bridge

volumes:
  static-volume: