name: GitHub Action Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # copy git 仓库到虚拟机上
    - name: 'Checkout codes'
      uses: actions/checkout@v4
    # 获取最新一条提交的git log  
    - name: Setup Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: pip
    # 安装项目依赖   
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # 运行测试用例
    - name: Run tests
      run: |
        python manage.py test

